[package]
name = "juggl"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
rand = "0.9.1"
memmap2 = "0.9"
rayon = "1.10"

[dev-dependencies]
tempfile = "3.8"
